spring.application.name=kite-backend
spring.mongodb.port=27017
spring.mongodb.host=localhost
spring.mongodb.database=kite-db
jwt.secret.key=${SECRET_KEY}
#in minutes
jwt.token.expiration=60
#in days
jwt.refresh.token.expiration=7
server.servlet.context-path=/kite/api/v1
spring.rabbitmq.username=user
spring.rabbitmq.password=password


langchain4j.google-ai-gemini.chat-model.api-key=${GEMINI_KEY}
langchain4j.google-ai-gemini.chat-model.model-name=gemini-3.1-flash-lite
langchain4j.google-ai-gemini.chat-model.log-requests=true
langchain4j.google-ai-gemini.chat-model.log-responses=true

# Springdoc OpenAPI Swagger Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha