spring.application.name=kite-backend
spring.mongodb.port=27017
spring.mongodb.host=localhost
spring.mongodb.database=kite-db
jwt.secret.key=0cf89ed81737c4b1eab59c0c12db12d4d5a572078792d802a37f636b9bfc4215
#in minutes
jwt.token.expiration=60
#in days
jwt.refresh.token.expiration=7
server.servlet.context-path=/kite/api/v1
spring.rabbitmq.username=user
spring.rabbitmq.password=password


langchain4j.ollama.chat-model.base-url=http://localhost:11434
langchain4j.ollama.chat-model.model-name=qwen2.5-coder:7b
langchain4j.ollama.chat-model.format=json
langchain4j.ollama.chat-model.log-requests=true
langchain4j.ollama.chat-model.log-responses=true