name: Test Backend & Generate Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Start Infrastructure (MongoDB Replica Set & RabbitMQ)
        run: |
          sudo echo "127.0.0.1 mongodb" | sudo tee -a /etc/hosts
          docker compose up -d
          docker wait mongo-init-replica

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Grant execute permission for mvnw
        run: chmod +x kite-backend/mvnw

      - name: Run Backend Tests & JaCoCo Report
        run: |
          cd kite-backend
          ./mvnw clean test

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: kite-backend/target/site/jacoco/jacoco.xml

      - name: Upload JaCoCo Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: kite-backend/target/site/jacoco/
